### ISSUE TITLE
Remove and repair coolant insulation

### ISSUE THREAD

**Issue by aaronreichmenberliner** [machinabio/crucible#10]
Coolant needs to be removed and repaired. 

Following coolant leak, the current insulation is logged and needs to be removed and replaced with new insulation.

The slit insulation is thermally weak. Replace with standard insulation.

**Comment by aaronreichmenberliner** [comment]
Ordered insulation from McMaster Carr. https://www.mcmaster.com/#catalog/123/3574/=1851qnp

Ultra-Flexible Foam Rubber Pipe Insulation, 3/8" Thick, 1/2" Insulation ID, 6' Length

**Comment by aaronreichmenberliner** [comment]
2/3 tubes insulated. Waiting for shipment from McMaster!

**Comment by miamirkovic** [comment]
Pulled tape off of old insulation carefully to minimize silicon oil leakage. Lifted tube out of insulation and carefully disposed of insulation and oil. Removed adapter from tube by first removing glue from rim of adapter with box cutter, crimping tube with pliers to release remaining glue, and pulling adapter off of tube with adjustable wrench. (Potentially able to slide insulation over adaptor but due to variability in elasticity of insulation, do not forcibly use this method.) Fit and trimmed new insulation to tube and replaced adaptor with wrench. @aaronreichmenberliner

**Comment by aaronreichmenberliner** [comment]
Still waiting on insulation. Should arrive evening 06/21/17. Will resume 06/22/17.

**Comment by aaronreichmenberliner** [comment]
Done.
